// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: UserMessage.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(a1d03e19cd8b0058);
CAPNP_DECLARE_SCHEMA(bf7856606fa0a119);
CAPNP_DECLARE_SCHEMA(c3ac6235e5336a90);
CAPNP_DECLARE_SCHEMA(b6a7bdf464bc8a98);
CAPNP_DECLARE_SCHEMA(fd690de1820ff912);

}  // namespace schemas
}  // namespace capnp


struct UserMessageType {
  UserMessageType() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  struct Command;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a1d03e19cd8b0058, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserMessageType::Command {
  Command() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    LOGON,
    SET_NICK,
    SEND_CHAT,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(bf7856606fa0a119, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserLogon {
  UserLogon() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c3ac6235e5336a90, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserSetNick {
  UserSetNick() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b6a7bdf464bc8a98, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserSendChat {
  UserSendChat() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(fd690de1820ff912, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class UserMessageType::Reader {
public:
  typedef UserMessageType Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline typename Command::Reader getCommand() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserMessageType::Builder {
public:
  typedef UserMessageType Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline typename Command::Builder getCommand();
  inline typename Command::Builder initCommand();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserMessageType::Pipeline {
public:
  typedef UserMessageType Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline typename Command::Pipeline getCommand();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserMessageType::Command::Reader {
public:
  typedef Command Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isLogon() const;
  inline bool hasLogon() const;
  inline  ::UserLogon::Reader getLogon() const;

  inline bool isSetNick() const;
  inline bool hasSetNick() const;
  inline  ::UserSetNick::Reader getSetNick() const;

  inline bool isSendChat() const;
  inline bool hasSendChat() const;
  inline  ::UserSendChat::Reader getSendChat() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserMessageType::Command::Builder {
public:
  typedef Command Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isLogon();
  inline bool hasLogon();
  inline  ::UserLogon::Builder getLogon();
  inline void setLogon( ::UserLogon::Reader value);
  inline  ::UserLogon::Builder initLogon();
  inline void adoptLogon(::capnp::Orphan< ::UserLogon>&& value);
  inline ::capnp::Orphan< ::UserLogon> disownLogon();

  inline bool isSetNick();
  inline bool hasSetNick();
  inline  ::UserSetNick::Builder getSetNick();
  inline void setSetNick( ::UserSetNick::Reader value);
  inline  ::UserSetNick::Builder initSetNick();
  inline void adoptSetNick(::capnp::Orphan< ::UserSetNick>&& value);
  inline ::capnp::Orphan< ::UserSetNick> disownSetNick();

  inline bool isSendChat();
  inline bool hasSendChat();
  inline  ::UserSendChat::Builder getSendChat();
  inline void setSendChat( ::UserSendChat::Reader value);
  inline  ::UserSendChat::Builder initSendChat();
  inline void adoptSendChat(::capnp::Orphan< ::UserSendChat>&& value);
  inline ::capnp::Orphan< ::UserSendChat> disownSendChat();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserMessageType::Command::Pipeline {
public:
  typedef Command Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserLogon::Reader {
public:
  typedef UserLogon Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasName() const;
  inline  ::capnp::Text::Reader getName() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserLogon::Builder {
public:
  typedef UserLogon Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasName();
  inline  ::capnp::Text::Builder getName();
  inline void setName( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initName(unsigned int size);
  inline void adoptName(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownName();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserLogon::Pipeline {
public:
  typedef UserLogon Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserSetNick::Reader {
public:
  typedef UserSetNick Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasNewName() const;
  inline  ::capnp::Text::Reader getNewName() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserSetNick::Builder {
public:
  typedef UserSetNick Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasNewName();
  inline  ::capnp::Text::Builder getNewName();
  inline void setNewName( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initNewName(unsigned int size);
  inline void adoptNewName(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownNewName();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserSetNick::Pipeline {
public:
  typedef UserSetNick Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserSendChat::Reader {
public:
  typedef UserSendChat Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasContents() const;
  inline  ::capnp::Text::Reader getContents() const;

  inline  ::int32_t getTimestamp() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserSendChat::Builder {
public:
  typedef UserSendChat Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasContents();
  inline  ::capnp::Text::Builder getContents();
  inline void setContents( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initContents(unsigned int size);
  inline void adoptContents(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownContents();

  inline  ::int32_t getTimestamp();
  inline void setTimestamp( ::int32_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserSendChat::Pipeline {
public:
  typedef UserSendChat Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline typename UserMessageType::Command::Reader UserMessageType::Reader::getCommand() const {
  return typename UserMessageType::Command::Reader(_reader);
}
inline typename UserMessageType::Command::Builder UserMessageType::Builder::getCommand() {
  return typename UserMessageType::Command::Builder(_builder);
}
#if !CAPNP_LITE
inline typename UserMessageType::Command::Pipeline UserMessageType::Pipeline::getCommand() {
  return typename UserMessageType::Command::Pipeline(_typeless.noop());
}
#endif  // !CAPNP_LITE
inline typename UserMessageType::Command::Builder UserMessageType::Builder::initCommand() {
  _builder.setDataField< ::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  return typename UserMessageType::Command::Builder(_builder);
}
inline  ::UserMessageType::Command::Which UserMessageType::Command::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::UserMessageType::Command::Which UserMessageType::Command::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool UserMessageType::Command::Reader::isLogon() const {
  return which() == UserMessageType::Command::LOGON;
}
inline bool UserMessageType::Command::Builder::isLogon() {
  return which() == UserMessageType::Command::LOGON;
}
inline bool UserMessageType::Command::Reader::hasLogon() const {
  if (which() != UserMessageType::Command::LOGON) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserMessageType::Command::Builder::hasLogon() {
  if (which() != UserMessageType::Command::LOGON) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::UserLogon::Reader UserMessageType::Command::Reader::getLogon() const {
  KJ_IREQUIRE((which() == UserMessageType::Command::LOGON),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserLogon>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UserLogon::Builder UserMessageType::Command::Builder::getLogon() {
  KJ_IREQUIRE((which() == UserMessageType::Command::LOGON),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserLogon>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserMessageType::Command::Builder::setLogon( ::UserLogon::Reader value) {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::LOGON);
  ::capnp::_::PointerHelpers< ::UserLogon>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::UserLogon::Builder UserMessageType::Command::Builder::initLogon() {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::LOGON);
  return ::capnp::_::PointerHelpers< ::UserLogon>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserMessageType::Command::Builder::adoptLogon(
    ::capnp::Orphan< ::UserLogon>&& value) {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::LOGON);
  ::capnp::_::PointerHelpers< ::UserLogon>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::UserLogon> UserMessageType::Command::Builder::disownLogon() {
  KJ_IREQUIRE((which() == UserMessageType::Command::LOGON),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserLogon>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserMessageType::Command::Reader::isSetNick() const {
  return which() == UserMessageType::Command::SET_NICK;
}
inline bool UserMessageType::Command::Builder::isSetNick() {
  return which() == UserMessageType::Command::SET_NICK;
}
inline bool UserMessageType::Command::Reader::hasSetNick() const {
  if (which() != UserMessageType::Command::SET_NICK) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserMessageType::Command::Builder::hasSetNick() {
  if (which() != UserMessageType::Command::SET_NICK) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::UserSetNick::Reader UserMessageType::Command::Reader::getSetNick() const {
  KJ_IREQUIRE((which() == UserMessageType::Command::SET_NICK),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserSetNick>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UserSetNick::Builder UserMessageType::Command::Builder::getSetNick() {
  KJ_IREQUIRE((which() == UserMessageType::Command::SET_NICK),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserSetNick>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserMessageType::Command::Builder::setSetNick( ::UserSetNick::Reader value) {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::SET_NICK);
  ::capnp::_::PointerHelpers< ::UserSetNick>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::UserSetNick::Builder UserMessageType::Command::Builder::initSetNick() {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::SET_NICK);
  return ::capnp::_::PointerHelpers< ::UserSetNick>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserMessageType::Command::Builder::adoptSetNick(
    ::capnp::Orphan< ::UserSetNick>&& value) {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::SET_NICK);
  ::capnp::_::PointerHelpers< ::UserSetNick>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::UserSetNick> UserMessageType::Command::Builder::disownSetNick() {
  KJ_IREQUIRE((which() == UserMessageType::Command::SET_NICK),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserSetNick>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserMessageType::Command::Reader::isSendChat() const {
  return which() == UserMessageType::Command::SEND_CHAT;
}
inline bool UserMessageType::Command::Builder::isSendChat() {
  return which() == UserMessageType::Command::SEND_CHAT;
}
inline bool UserMessageType::Command::Reader::hasSendChat() const {
  if (which() != UserMessageType::Command::SEND_CHAT) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserMessageType::Command::Builder::hasSendChat() {
  if (which() != UserMessageType::Command::SEND_CHAT) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::UserSendChat::Reader UserMessageType::Command::Reader::getSendChat() const {
  KJ_IREQUIRE((which() == UserMessageType::Command::SEND_CHAT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserSendChat>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UserSendChat::Builder UserMessageType::Command::Builder::getSendChat() {
  KJ_IREQUIRE((which() == UserMessageType::Command::SEND_CHAT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserSendChat>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserMessageType::Command::Builder::setSendChat( ::UserSendChat::Reader value) {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::SEND_CHAT);
  ::capnp::_::PointerHelpers< ::UserSendChat>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::UserSendChat::Builder UserMessageType::Command::Builder::initSendChat() {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::SEND_CHAT);
  return ::capnp::_::PointerHelpers< ::UserSendChat>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserMessageType::Command::Builder::adoptSendChat(
    ::capnp::Orphan< ::UserSendChat>&& value) {
  _builder.setDataField<UserMessageType::Command::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, UserMessageType::Command::SEND_CHAT);
  ::capnp::_::PointerHelpers< ::UserSendChat>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::UserSendChat> UserMessageType::Command::Builder::disownSendChat() {
  KJ_IREQUIRE((which() == UserMessageType::Command::SEND_CHAT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UserSendChat>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserLogon::Reader::hasName() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserLogon::Builder::hasName() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader UserLogon::Reader::getName() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder UserLogon::Builder::getName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserLogon::Builder::setName( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder UserLogon::Builder::initName(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void UserLogon::Builder::adoptName(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> UserLogon::Builder::disownName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserSetNick::Reader::hasNewName() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserSetNick::Builder::hasNewName() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader UserSetNick::Reader::getNewName() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder UserSetNick::Builder::getNewName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserSetNick::Builder::setNewName( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder UserSetNick::Builder::initNewName(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void UserSetNick::Builder::adoptNewName(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> UserSetNick::Builder::disownNewName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserSendChat::Reader::hasContents() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserSendChat::Builder::hasContents() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader UserSendChat::Reader::getContents() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder UserSendChat::Builder::getContents() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserSendChat::Builder::setContents( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder UserSendChat::Builder::initContents(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void UserSendChat::Builder::adoptContents(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> UserSendChat::Builder::disownContents() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::int32_t UserSendChat::Reader::getTimestamp() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int32_t UserSendChat::Builder::getTimestamp() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void UserSendChat::Builder::setTimestamp( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}


CAPNP_END_HEADER

